### ISSUE TITLE
tool test produced a empty glb file

### ISSUE THREAD

**Issue by zynga-jpetersen** [msfeldstein/glb-utils#1]
Greetings!

So I'm not sure if this tool is ready for primetime yet, but when I ran it on a test gltf file, it produced an empty glb file.

I've attached the file if you wanted to check it out. The assets pass both the validator and work in the three.js viewer, so I believe them to correctly match the gltf standard.

Also that draco integration to three.js seems pretty interesting, it would be great if I could piggy back on your tool to have it run the draco process to compress my model and add the extension data. But that might be beyond the scope of what you were thinking.

[cube_test.zip](https://github.com/msfeldstein/glb-utils/files/1418855/cube_test.zip)

Thanks.

**Comment by msfeldstein** [comment]
i'll take a look!  I definitely wouldn't say any of this is prime-time ready i mostly made it public to share with a couple people but i'd like to get it there.

If you want draco compression and are starting with fbx you might check out the [FBX2glTF](https://github.com/facebookincubator/FBX2glTF) project, otherwise i will hopefully have this pipeline working soon.

**Comment by msfeldstein** [comment]
I ran glb-pack /path/to/just_cube.gltf and ended up with this glb, is this not what you expect?
<img width="1415" alt="screen shot 2017-10-26 at 8 13 48 am" src="https://user-images.githubusercontent.com/161135/32061134-ae41538a-ba25-11e7-885b-55e3c3dfcdc0.png">
[just_cube.glb.zip](https://github.com/msfeldstein/glb-utils/files/1418942/just_cube.glb.zip)

**Comment by msfeldstein** [comment]
Oh if you're trying to run the draco compressor, yeah that definitely doesn't work quite yet

**Comment by zynga-jpetersen** [comment]
hmm, ok, I ran the tool on a mac with the following args:
./node_modules/.bin/glb-pack ./static/cube_test/just_cube.gltf

[just_cube.glb.zip](https://github.com/msfeldstein/glb-utils/files/1418960/just_cube.glb.zip)

it produced that asset.

As for the draco stuff, that was just a side topic from looking at your tool.

**Comment by zynga-jpetersen** [comment]
Also in terms of the draco tools work, I've realized the draco/google people are already working on that part https://github.com/fanzhanggoogle/gltf-pipeline/pull/2 . So not reason to duplicate that effort.

**Comment by msfeldstein** [comment]
That's odd it definitely works for me.  I'm cleaning up the code base a bit and adding some tests so let me ask you to try it again shortly on latest.

**Comment by msfeldstein** [comment]
can you pull master (v1.0.5) and tell me if this still happens?  I think you might have grabbed some broken intermediate commit

**Comment by zynga-jpetersen** [comment]
I was actually using your npm version, but I'll try master. one sec.

**Comment by zynga-jpetersen** [comment]
hmm, still zero bytes, with call:
./bin/glb-pack.js ./cube_test/just_cube.gltf
with same assets as before:
[cube_test.zip](https://github.com/msfeldstein/glb-utils/files/1419778/cube_test.zip)

**Comment by zynga-jpetersen** [comment]
I'm running node version v6.11.1, if maybe that is significant.

**Comment by msfeldstein** [comment]
Interesting i just tried it on 6.11.1 and yeah, i see the same problem.  I
fixed it in v1.0.6 if you want to update and verify

**Comment by zynga-jpetersen** [comment]
That worked, thanks!
